server {
    listen 6900;
    listen [::]:6900;

    server_name localhost;

    root /home/will/willsite_ui/src;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    access_log /var/log/nginx/willsite_ui_access.log;
    error_log /var/log/nginx/willsite_ui_error.log;
}